#+TITLE: Music Room API Logbook


* Playlist

<2026-09-10 Thu>:05:30 : comment faire pour stocker les musiques d'une playlist dans l'ordre en base de données
sachant que l'ordre peut changer.
<2026-09-10 Thu>:05:51 : quel mécanisme implémenter pour protéger les accès concurrents aux playlists, notamment
pour gérer les insertions, deletions sans que les autres utilisateurs soient dans des états invalides.

<2026-09-12 Sat>:06:38 : on a besoin d'identifier les musiques d'une playlist, on lui donne un ID ou alors on
les identifie par leur index dans la playlist ? Les index peuvent potentiellement poser problème dans des situations
d'accès concurrents.

Specs :
- On doit pouvoir identifier de manière unique les musiques dans une playlist
- On doit lever une erreur si un utilisateur essaye de supprimer une musique qui n'a pas été ajouté par lui même.
  Sauf si l'utilisateur est l'owner de la playlist.

<2026-09-12 Sat>:06:46 : mettre une limite sur le nombre de musiques possibles dans une playlist.

<2026-09-12 Sat>:18:31 : implémenter un service de permission pour connaitre les permissions d'un utilisateur
sur une playlist.

** Resources
https://www.postgresql.org/docs/current/datatype-json.html une première solution naïve serait de stocker les playlists
en tant que JSON

https://softwareengineering.stackexchange.com/questions/195308/storing-a-re-orderable-list-in-a-database
plusieurs éléments de réponse sont donnés pour pouvoir stocker des listes réordonnable

* Permissions

<2026-09-10 Thu>:05:35 : comment implémenter les permissions
